courtcanva/cc-multiverse

.github/pull_request_template.md
.github/workflows/sanity-check.yml
README.md

- Link to Jira ticket here: `N/A`
- Link to Figma: `N/A`
- No screenshot is available for this pr, but you will find GitHub Action running in this commit
You should find [feat: add pr template for developers](https://github.com/courtcanva/cc-multiverse/pull/7/commits/51d6bf61c63bf2f9a39a169c4d3bc3e5e21ef693) commit failed due to type in the workflow file, and [fix: typo in sanity-check workflow](https://github.com/courtcanva/cc-multiverse/pull/7/commits/64d1c61135d76c9835165ae37275ced67e257669) commit came out success.

[CC-xx] Set up GitHub action and pr template

---

apps/galaxy/src/layouts/Footer.tsx
apps/galaxy/src/layouts/index.tsx
apps/galaxy/src/modules/auth/SignInForm/index.tsx
packages/ui-chakra/src/index.ts

- Link to Jira ticket here:https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-41

[CC-41] sign-in & layout responsive

---

apps/galaxy/src/pages/_app.tsx

fix: code fix by mistake deleted

---

apps/galaxy/src/__tests__/modules/auth/SignUpForm/SignUpForm.test.tsx
apps/galaxy/src/modules/auth/SignUpForm/CompanyInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/RegisterInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/SignUpFrom.schema.tsx
apps/galaxy/src/modules/auth/SignUpForm/StaffInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/index.tsx
packages/ui-chakra/src/base/Tab/StepTab.tsx

- Link to Jira ticket here: 
- https://leonhard.atlassian.net/browse/CC-46
- https://leonhard.atlassian.net/browse/CC-48

[CC-46&48: Bugfix] update error message of password & remove back button in each step

---

apps/galaxy/src/__tests__/modules/auth/SignInForm/SignIn.test.tsx
apps/galaxy/src/__tests__/modules/auth/SignUpForm/SignUpForm.test.tsx
apps/galaxy/src/__tests__/services/signin/useSignIn.test.tsx
apps/galaxy/src/modules/auth/SignInForm/SignInForm.tsx
apps/galaxy/src/modules/auth/SignUpForm/index.tsx
packages/ui-chakra/src/base/Button/Button.tsx

- Link to Jira ticket here: https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-45

[CC-45: Bugfix] User need to be able to navigate between sign in and sign up page

---

apps/galaxy/next.config.js

[CC-44: BugFix] uat-url-needs-to-be-updated-without-html

---

apps/galaxy/src/modules/auth/SignUpForm/CompanyInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/RegisterInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/SignUpFrom.schema.tsx
apps/galaxy/src/modules/auth/SignUpForm/StaffInfoPage.tsx

- Link to Jira ticket here:https://leonhard.atlassian.net/browse/CC-47

[Bugfix-CC-47] Address detail of both company info form and staff info form should be an optional field

---

apps/galaxy/src/services/utils/axios.ts
package-lock.json

- Link to Jira ticket here:https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-53
https://user-images.githubusercontent.com/49120762/200459862-57b45b77-cad6-419f-b303-173ceebbd07e.mov

[CC-53: BugFix] Operation to sign up a franchisee should not include any jwt token in the header when requesting

---

apps/galaxy/src/__tests__/modules/auth/SignInForm/SignIn.test.tsx
apps/galaxy/src/__tests__/modules/auth/SignUpForm/SignUpForm.test.tsx
apps/galaxy/src/modules/auth/SignInForm/SignInForm.tsx
apps/galaxy/src/modules/auth/SignUpForm/RegisterInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/index.tsx
packages/ui-chakra/src/base/Button/Button.tsx
packages/ui-chakra/src/index.ts

- Link to Jira ticket here: https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-51

[BugFix: CC-51] Link to sign up/sign in page need to be distinguishable from normal text

---

apps/galaxy/src/layouts/index.tsx
apps/galaxy/src/modules/auth/SignInForm/index.tsx
apps/galaxy/src/modules/auth/SignUpForm/index.tsx

https://user-images.githubusercontent.com/49120762/201048239-065c3186-0c07-4443-8f84-6311b0c66c72.mov

[CC-54: Feature] Sign-up Responsive

---

apps/galaxy/src/modules/auth/SignInForm/index.tsx
apps/galaxy/src/modules/auth/SignUpForm/CompanyInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/StaffInfoPage.tsx
apps/galaxy/src/modules/auth/SignUpForm/formConfig.ts
packages/ui-chakra/src/base/Input/FormGroupInput.tsx
packages/ui-chakra/src/base/index.ts
packages/ui-chakra/src/index.ts

- Link to Jira ticket here:https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-49
https://user-images.githubusercontent.com/49120762/201239335-74526f96-85e7-451e-9257-ae01f98d7332.mov

[CC-49: BugFix] Mismatch of mobile number between frontend validation and backend validation

---

apps/galaxy/src/__tests__/modules/auth/SignUpForm/SignUpForm.test.tsx
apps/galaxy/src/__tests__/services/signup/useSignUp.test.tsx
apps/galaxy/src/modules/ServiceAreaSelectionForm/index.tsx
apps/galaxy/src/modules/auth/SignUpForm/CompanyInfoPage.tsx
apps/galaxy/src/services/signup/useSignUp.ts
apps/galaxy/src/services/utils/axios.ts

- Link to Jira ticket here: https://leonhard.atlassian.net/browse/CC-57

[Bugfix-CC-57]check duplicate abn

---

apps/galaxy/src/pages/index.tsx

- Link to Jira ticket here: https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-56
- Link to Figma: none

[Feature-cc-56] Sign out button

---

apps/galaxy/src/layouts/index.tsx
apps/galaxy/src/modules/ServiceAreaSelectionForm/index.tsx
apps/galaxy/src/pages/404.tsx
apps/galaxy/src/pages/index.tsx

- Link to Jira ticket here:https://leonhard.atlassian.net/jira/software/projects/CC/boards/2/backlog?cloudId=5b66e27f-f385-452a-b0ac-5cdd0497ae92&selectedIssue=CC-58

cc-58 Responsive for index and 404 page

---

apps/galaxy/src/__tests__/services/ServiceAreaSelection/useServiceArea.test.tsx
apps/galaxy/src/modules/ServiceAreaSelectionForm/ServiceAreaSelectionForm.tsx
apps/galaxy/src/modules/auth/EmailVerification/index.tsx
apps/galaxy/src/services/servicearea/useServiceArea.ts

CC-58 bugfix: router fix

---

apps/galaxy/src/__tests__/services/signup/useSignUp.test.tsx
apps/galaxy/src/services/signup/useSignUp.ts

- Link to Jira ticket here:  https://leonhard.atlassian.net/jira/software/projects/CC/boards/2?selectedIssue=CC-59

fix: postcode payload mismatch

---

apps/galaxy/.husky/commit-msg
apps/galaxy/.husky/pre-commit
package.json

bugfix:try add husky in galaxy

---

.dockerignore
apps/galaxy/Dockerfile
apps/galaxy/next.config.js
apps/galaxy/package.json
apps/galaxy/src/modules/auth/SignInForm/SignInForm.tsx
apps/galaxy/src/modules/auth/SignUpForm/RegisterInfoPage.tsx
apps/galaxy/src/pages/_app.tsx
apps/galaxy/src/pages/api/healthcheck.js
buildspec-ecs.yml
docker-compose.yml
package.json
taskdef-uat.json

Cc 60 bugfix deploy

---

apps/galaxy/src/__tests__/modules/auth/SignInForm/SignIn.test.tsx
apps/galaxy/src/__tests__/modules/auth/SignUpForm/SignUpForm.test.tsx

bugfix: test update

---

taskdef-uat.json

Add Container Log 

---

apps/galaxy/src/__tests__/services/useVerifyEmail.test.tsx
apps/galaxy/src/services/verify-email/useVerifyEmail.ts

CC-63 bugfix: router udpate
